export const socLinks = {
  facebook: {
    title: "",
    link: "https://www.facebook.com/profspilka.novaposhta",
    iconRed: "",
    iconWhite: "",
    iconColor: "",
    style: "",
  },
  instagram: {
    title: "",
    link: "https://www.instagram.com/profspilka.np/",
    iconRed: "",
    iconWhite: "",
    iconColor: "",
    style: "",
  },
  telegram: {
    title: "",
    link: "https://t.me/profspilka_np",
    iconRed: "",
    iconWhite: "",
    iconColor: "",
    style: "",
  },
  youTube: {
    title: "",
    link: "https://www.youtube.com/c/%D0%9F%D0%A0%D0%9E%D0%A4%D0%A1%D0%9F%D0%86%D0%9B%D0%9A%D0%90%D0%9D%D0%9F",
    iconRed: "",
    iconWhite: "",
    iconColor: "",
    style: "",
  },
  messenger: {
    title: "",
    link: "https://www.messenger.com/",
    iconRed: "",
    iconWhite: "",
    iconColor: "",
    style: "",
  },
  viber: {
    title: "",
    link: "https://invite.viber.com/?g2=AQB5jyDD9hRH2E4T1sgP3mF5DLFT3M6rGUUWfv2%2FHB1AddnNt8Vy6o2DXH793wQk/",
    iconRed: "",
    iconWhite: "",
    iconColor: "",
    style: "",
  },
};
