export default function robots() {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/pro-nas",
          "/blanky",
          "/novyny",
          "/novyny/*",
          "/foto",
          "/foto/*",
          "/kontakty",
          "/poshuk-po-saytu",
          "/kolektyvnyy-dohovir",
          "/ppo",
          "/zakhyst-trudovykh-prav",
          "/materialna-dopomoga",
          "/dozvillya-ta-sport",
          "/ya-profspilka",
          "/zvernennya",
          "/ozdorovlennya",
          "/yak-vstupyty",

          "/uk/",
          "/uk/pro-nas",
          "/uk/blanky",
          "/uk/novyny",
          "/uk/novyny/*",
          "/uk/foto",
          "/uk/foto/*",
          "/uk/kontakty",
          "/uk/poshuk-po-saytu",
          "/uk/kolektyvnyy-dohovir",
          "/uk/ppo",
          "/uk/zakhyst-trudovykh-prav",
          "/uk/materialna-dopomoga",
          "/uk/dozvillya-ta-sport",
          "/uk/ya-profspilka",
          "/uk/zvernennya",
          "/uk/ozdorovlennya",
          "/uk/yak-vstupyty",
          "/en/",
          "/en/pro-nas",
          "/en/blanky",
          "/en/novyny",
          "/en/novyny/*",
          "/en/foto",
          "/en/foto/*",
          "/en/kontakty",
          "/en/poshuk-po-saytu",
          "/en/kolektyvnyy-dohovir",
          "/en/ppo",
          "/en/zakhyst-trudovykh-prav",
          "/en/materialna-dopomoga",
          "/en/dozvillya-ta-sport",
          "/en/ya-profspilka",
          "/en/zvernennya",
          "/en/ozdorovlennya",
          "/en/yak-vstupyty",
        ],
        disallow: ["/uk/admin", "/en/admin", "/subscription", "/signin"],
      },
    ],
  };
}
