// export default function robots() {
//   return {
//     rules: {
//       userAgent: "*",
//       allow: "/",
//       allow: "/pro-nas",
//       allow: "/blanky",
//       allow: "/novyny",
//       allow: "/foto",
//       allow: "/kontakty",
//       allow: "/poshuk-po-saytu",
//       allow: "/kolektyvnyy-dohovir",
//       allow: "/ppo",
//       allow: "/zakhyst-trudovykh-prav",
//       allow: "/materialna-dopomoga",
//       allow: "/dozvillya-ta-sport",
//       allow: "/ya-profspilka",
//       allow: "/zvernennya",
//       disallow: "/subscription",
//       disallow: "/signin",
//       disallow: "/uk/admin",
//     },
//     // sitemap: 'https://наш-домен/sitemap.xml',
//   };
// }

export default function robots() {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/", // корінь сайту
          "/pro-nas",
          "/blanky",
          "/novyny",
          "/foto",
          "/kontakty",
          "/poshuk-po-saytu",
          "/kolektyvnyy-dohovir",
          "/ppo",
          "/zakhyst-trudovykh-prav",
          "/materialna-dopomoga",
          "/dozvillya-ta-sport",
          "/ya-profspilka",
          "/zvernennya",
          // Додаємо версії для локалей:
          "/uk/",
          "/uk/pro-nas",
          "/uk/blanky",
          "/uk/novyny",
          "/uk/foto",
          "/uk/kontakty",
          "/uk/poshuk-po-saytu",
          "/uk/kolektyvnyy-dohovir",
          "/uk/ppo",
          "/uk/zakhyst-trudovykh-prav",
          "/uk/materialna-dopomoga",
          "/uk/dozvillya-ta-sport",
          "/uk/ya-profspilka",
          "/uk/zvernennya",
          "/en/",
          "/en/pro-nas",
          "/en/blanky",
          "/en/novyny",
          "/en/foto",
          "/en/kontakty",
          "/en/poshuk-po-saytu",
          "/en/kolektyvnyy-dohovir",
          "/en/ppo",
          "/en/zakhyst-trudovykh-prav",
          "/en/materialna-dopomoga",
          "/en/dozvillya-ta-sport",
          "/en/ya-profspilka",
          "/en/zvernennya",
        ],
        disallow: ["/uk/admin", "/en/admin", "/subscription", "/signin"],
      },
    ],
  };
}
